### ISSUE TITLE
[Hosted Service] Indexer stucks at random block height

### ISSUE THREAD

**Issue by chrisais9** [enviodev/hyperindex#185] opened 2024-09-09 10:23 UTC
**Describe the bug**
Indexer on Hosted Service stucks on random block height.

**To Reproduce** Steps to reproduce the behavior:

1. Go to [https://envio.dev/app/hashscape/salt-dex-indexer](https://envio.dev/app/hashscape/salt-dex-indexer)
2. See dashboard, logs

**Expected behavior** Should be able sync to latest block height without stucking

**Screenshots** If applicable, add screenshots to help explain your problem.

**Local (please complete the following information):**

* Envio version: N/A (hosted service)
* Node version: N/A (hosted service)
* pnpm version: N/A (hosted service)
* Docker version (if running locally): N/A (hosted service)

**Hosted Service (please complete the following information):**

* Envio version: 2.2.0
* Link to the deployed indexer: [https://envio.dev/app/hashscape/salt-dex-indexer](https://envio.dev/app/hashscape/salt-dex-indexer)

**Additional context**

* @JasoonS have [restarted](https://discord.com/channels/1093188574305857656/1141661419457216623/1282597224680914944) the indexer. But stuck after a while.
* I assume not code error. It stucks at random height. Tested on multiple deployments.
* No error logs showing.

**Comment by JasoonS** [comment] 2024-09-09 10:51
I assume it syncs fully if you run it locally? The freezing only happens in the hosted service?

**Comment by chrisais9** [comment] 2024-09-09 11:25
I haven’t sync 100% on local. But other deployment in hosted service have synced over stucked block height with same codebases

**Comment by JonoPrest** [comment] 2024-09-11 14:06
Hey @chrisais9, any chance you can share repo or a way to reproduce? It looks like it's busy syncing on the hosted service.

**Comment by JonoPrest** [comment] 2024-09-12 08:21
Hey @chrisais9,

Thanks for sharing 🙏🏼. 

When you say the indexer was stuck, does it crash or just appear to not be moving/no more data appearing in your DB?

A reason it can appear stuck is if a batch of events takes a really long time to process. In the hosted service the `MAX_BATCH_SIZE` is currently fixed at 5000 (events per batch). This should be configurable soon though. But locally you can set this environment variable if you want to change it.

Typically I've only seen this behaviour with slow async calls in handlers. Say if you make an non-cached RPC call on a handler and it has a 1 second round trip. For a batch of 5000 events that would be over an hour before the batch reflects any change in the UI or DB. In other cases it could be that just one async call is hanging in a handler and stopping the batch from continuing.

I ran your indexer locally for some time and it seems that handlers are not taking excessively long to run so I imagine it could be one of your async requests hanging. My suggestion would be to implement timeouts with retries on your async calls. Or you can event choose to crash your indexer on a timeout since there is good restart recovery on the hosted service.

**Comment by JonoPrest** [comment] 2024-09-12 08:22
> Found dumped error log. Not sure if is related to this issue.
> 
> ```
> {"log.level":"error","@timestamp":"2024-09-09T07:15:34.180Z","process.pid":1440,"host.hostname":"id-e5cfb43-3062ee3-salt-dex-indexer-7579fc784b-kn5zh","ecs.version":"1.6.0","msg":"Indexer has failed with an unxpected error","err":{"RE_EXN_ID":"FetchState.UnexpectedRegisterDoesNotExist/1","_1":{"TAG":"DynamicContract","_0":{"blockNumber":12904924,"logIndex":218}}}}
> ```
> 
> <img alt="" width="1728" src="https://private-user-images.githubusercontent.com/40062271/365769605-6eac518d-635d-40ba-9afb-c4b665f149d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxMjcxNDUsIm5iZiI6MTcyNjEyNjg0NSwicGF0aCI6Ii80MDA2MjI3MS8zNjU3Njk2MDUtNmVhYzUxOGQtNjM1ZC00MGJhLTlhZmItYzRiNjY1ZjE0OWQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTEyVDA3NDA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMDRmZWM0N2MwMjRmNjVmNmM3ZTc3OTI2YmYxMTNiYzc0YThhMWI1OWViYmEyMWM1OWEwMTFkODY0MTA4ZTAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uu8dFyh4rbp2jcjPcHqr4LRc8zc-vX0OFM8WFn9lhNY">
> > https://envio.dev/app/hashscape/salt-dex-indexer/e5cfb43/runtime-logs

This error log you've posted is unexpected to see and I will investigate it further but it's unrelated to an indexer appearing stuck. Since it would have caused a crash and restart.

**Comment by JonoPrest** [comment] 2024-09-13 07:44
Thanks @chrisais9, I'll close this for now. If you are still experiencing issues after implementing the above let us know and we can reopen.

**Closed by JonoPrest** 2024-09-13 07:44 UTC
Labels: Bug, P3 (Medium Priority)
